apiVersion: v1
kind: Service
metadata:
  name: pub-subapi-svc-service
spec:
  selector:
    app: pub-subapi-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
